//! Shared demo content for the eframe and Bevy demo apps.
//!
//! Contains the 7-page markdown demo generated by `define_markdown_app!`,
//! plus the `auto_unmute` ECS system. Both `eframe_demo` and `bevy_demo`
//! depend on this crate for the generated types and render functions.

use bevy_ecs::prelude::*;
use litui::*;

mod pages {
    use egui;
    use litui::*;

    define_markdown_app! {
        parent: "content/_app.md",
        "content/about.md",
        "content/text_showcase.md",
        "content/list_demo.md",
        "content/table_demo.md",
        "content/style_gallery.md",
        "content/form_demo.md",
        "content/monitor.md",
    }
}

pub use pages::*;

impl Resource for Page {}
impl Resource for AppState {}

/// ECS system: automatically uncheck "muted" when volume exceeds 80%.
pub fn auto_unmute(mut state: ResMut<'_, AppState>) {
    if state.volume > 80.0 {
        state.muted = false;
    }
}
