//! Example: integrating 3rd-party egui widget crates with the markdown macro.
//!
//! Demonstrates two patterns:
//! - **Pattern A (built-in)**: `[double_slider]` directive handled by the macro
//!   (requires `egui_double_slider` crate in dependencies)
//! - **Pattern B (manual)**: Hand-coded widgets alongside macro-generated content
//!   (for complex widgets that don't fit the directive model)

#![expect(clippy::unwrap_used)]

use eframe::egui;
use litui::*;

fn main() -> eframe::Result {
    let (render, state) = include_markdown_ui!("content.md");

    let options = eframe::NativeOptions::default();
    eframe::run_native(
        "3rd-Party Widgets Example",
        options,
        Box::new(move |_cc| {
            Ok(Box::new(App {
                render,
                state,
                // Manual widget state (Pattern B)
                selected_tags: vec![false; TAGS.len()],
                color: egui::Color32::from_rgb(100, 150, 230),
            }) as Box<dyn eframe::App>)
        }),
    )
}

const TAGS: &[&str] = &[
    "Rust",
    "egui",
    "Markdown",
    "Proc-macro",
    "UI",
    "Compile-time",
];

struct App<S> {
    render: fn(&mut egui::Ui, &mut S),
    state: S,
    // Pattern B: state for hand-coded widgets
    selected_tags: Vec<bool>,
    color: egui::Color32,
}

impl<S> eframe::App for App<S> {
    fn update(&mut self, ctx: &egui::Context, _frame: &mut eframe::Frame) {
        egui::CentralPanel::default().show(ctx, |ui| {
            egui::ScrollArea::vertical().show(ui, |ui| {
                // ── Pattern A: macro-generated content ──
                // Includes [double_slider] directives handled by the macro.
                // The egui_double_slider crate is a dependency of THIS crate,
                // and the macro emits code that references it.
                (self.render)(ui, &mut self.state);

                ui.separator();

                // ── Pattern B: hand-coded widgets ──
                // For complex widgets that don't fit the macro's directive model,
                // render them in app code alongside the macro-generated content.
                ui.heading("Manual Widgets (Pattern B)");
                ui.label("These widgets are hand-coded in the app, not generated by the macro.");

                ui.add_space(8.0);
                ui.strong("Tag selector:");
                ui.horizontal_wrapped(|ui| {
                    for (i, &tag) in TAGS.iter().enumerate() {
                        ui.toggle_value(&mut self.selected_tags[i], tag);
                    }
                });

                let selected: Vec<&str> = TAGS
                    .iter()
                    .zip(self.selected_tags.iter())
                    .filter(|(_, sel)| **sel)
                    .map(|(&tag, _)| tag)
                    .collect();
                ui.label(format!("Selected: {}", selected.join(", ")));

                ui.add_space(8.0);
                ui.strong("Color picker:");
                ui.color_edit_button_srgba(&mut self.color);
                ui.label(format!(
                    "Color: #{:02X}{:02X}{:02X}",
                    self.color.r(),
                    self.color.g(),
                    self.color.b()
                ));
            });
        });
    }
}
