//! Step-by-step guides for building UIs with litui.
//!
//! Start with [Hello Markdown](_01_hello_markdown) and work through in order.
//! Each tutorial includes screenshots generated by the kittest harness and
//! references a runnable example you can try with `cargo run -p <example>`.
//!
//! | # | Tutorial | Example |
//! |---|----------|---------|
//! | 01 | [Hello Markdown](_01_hello_markdown) | `markdown_macro_example` |
//! | 02 | [Frontmatter Styles](_02_frontmatter_styles) | `widgets_example` |
//! | 03 | [Tables](_03_tables) | `eframe_demo` |
//! | 04 | [Widgets](_04_widgets) | `widgets_example` |
//! | 05 | [Selectors and Styled Spans](_05_selectors_and_spans) | `selectors_example` |
//! | 06 | [Styled Containers](_06_styled_containers) | `selectors_example` |
//! | 07 | [Multi-Page Apps](_07_multi_page_apps) | `eframe_demo` |
//! | 08 | [Images](_08_images) | `markdown_macro_example` |
//! | 09 | [Third-Party Widgets](_09_third_party_widgets) | `third_party_widgets` |
//! | 10 | [Bevy Integration](_10_bevy_integration) | `bevy_demo` |
//! | 11 | [Game UI Patterns](_11_game_ui_patterns) | `game_demo` |

#[expect(clippy::doc_include_without_cfg)]
#[doc = include_str!("../../tutorials/01_hello_markdown.md")]
pub mod _01_hello_markdown {}

#[expect(clippy::doc_include_without_cfg)]
#[doc = include_str!("../../tutorials/02_frontmatter_styles.md")]
pub mod _02_frontmatter_styles {}

#[expect(clippy::doc_include_without_cfg)]
#[doc = include_str!("../../tutorials/03_tables.md")]
pub mod _03_tables {}

#[expect(clippy::doc_include_without_cfg)]
#[doc = include_str!("../../tutorials/04_widgets.md")]
pub mod _04_widgets {}

#[expect(clippy::doc_include_without_cfg)]
#[doc = include_str!("../../tutorials/05_selectors_and_spans.md")]
pub mod _05_selectors_and_spans {}

#[expect(clippy::doc_include_without_cfg)]
#[doc = include_str!("../../tutorials/06_styled_containers.md")]
pub mod _06_styled_containers {}

#[expect(clippy::doc_include_without_cfg)]
#[doc = include_str!("../../tutorials/07_multi_page_apps.md")]
pub mod _07_multi_page_apps {}

#[expect(clippy::doc_include_without_cfg)]
#[doc = include_str!("../../tutorials/08_images.md")]
pub mod _08_images {}

#[expect(clippy::doc_include_without_cfg)]
#[doc = include_str!("../../tutorials/09_third_party_widgets.md")]
pub mod _09_third_party_widgets {}

#[expect(clippy::doc_include_without_cfg)]
#[doc = include_str!("../../tutorials/10_bevy_integration.md")]
pub mod _10_bevy_integration {}

#[expect(clippy::doc_include_without_cfg)]
#[doc = include_str!("../../tutorials/11_game_ui_patterns.md")]
pub mod _11_game_ui_patterns {}
